# Generated by Django 4.2.3 on 2025-12-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("superadmin", "超级管理员"), ("site_admin", "场站管理员")],
                default="superadmin",
                max_length=20,
                verbose_name="用户角色",
            ),
        ),
    ]
