# Generated by Django 4.2.3 on 2025-12-12 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="分类名称"),
                ),
                ("description", models.TextField(blank=True, verbose_name="分类描述")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="分类编码"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "备件分类",
                "verbose_name_plural": "备件分类",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="SparePart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="备件名称")),
                (
                    "model",
                    models.CharField(
                        default="UNKNOWN", max_length=200, verbose_name="备件型号"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="备件描述")),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="当前数量"),
                ),
                (
                    "alarm_qty",
                    models.PositiveIntegerField(default=5, verbose_name="库存预警数量"),
                ),
                ("location", models.CharField(max_length=200, verbose_name="备件位置")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="spare_parts/",
                        verbose_name="备件图片",
                    ),
                ),
                (
                    "supplier",
                    models.CharField(blank=True, max_length=100, verbose_name="供应商名称"),
                ),
                (
                    "supplier_code",
                    models.CharField(blank=True, max_length=100, verbose_name="供应商编码"),
                ),
                (
                    "procurement_days",
                    models.PositiveIntegerField(default=7, verbose_name="采购周期（天）"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "活跃"),
                            ("inactive", "停用"),
                            ("obsolete", "已淘汰"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "last_purchase_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后采购日期"),
                ),
                (
                    "last_use_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后使用日期"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spare_parts",
                        to="SparePart.category",
                        verbose_name="备件分类",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_spare_parts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spare_parts",
                        to="sites.site",
                        verbose_name="所属场站",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_spare_parts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "备件",
                "verbose_name_plural": "备件管理",
                "ordering": ["site", "name"],
                "unique_together": {("name", "site")},
            },
        ),
        migrations.CreateModel(
            name="SparePartTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("in", "入库"), ("out", "出库")],
                        max_length=10,
                        verbose_name="操作类型",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="数量")),
                ("reason", models.CharField(max_length=200, verbose_name="操作原因")),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spare_part_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
                (
                    "spare_part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="SparePart.sparepart",
                        verbose_name="备件",
                    ),
                ),
            ],
            options={
                "verbose_name": "备件出入库记录",
                "verbose_name_plural": "备件出入库记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
