# Generated by Django 4.2.3 on 2025-12-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SparePart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sparepart",
            name="location",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="备件位置"
            ),
        ),
    ]
