# Generated by Django 4.2.3 on 2025-12-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SparePart", "0002_alter_sparepart_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sparepart",
            name="location",
            field=models.CharField(max_length=200, verbose_name="备件位置"),
        ),
    ]
