# Generated by Django 4.2.3 on 2025-12-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SparePart", "0003_alter_sparepart_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sparepart",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="sparepart",
            name="location",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="备件位置"
            ),
        ),
    ]
