# Generated by Django 4.2.3 on 2025-12-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="场站名称"),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="场站代码"),
                ),
                ("address", models.CharField(max_length=200, verbose_name="详细地址")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="联系电话"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="联系邮箱"),
                ),
                (
                    "manager_name",
                    models.CharField(blank=True, max_length=50, verbose_name="负责人姓名"),
                ),
                ("description", models.TextField(blank=True, verbose_name="场站描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "场站",
                "verbose_name_plural": "场站管理",
                "ordering": ["code"],
            },
        ),
    ]
